services:
    db:
      container_name: postgres-db
      image: postgres  # Use the official PostgreSQL image
      env_file:
        - database.env
      environment:
        - TZ=Asia/Kathmandu
        - PGTZ=Asia/Kathmandu
        - POSTGRES_USER=postgres
      ports:
          - "5432:5432"  # Map the container's port 5432 to your host's port 5432
      volumes:
          - postgres_data:/var/lib/postgresql/data  # Persist database data

volumes:
    postgres_data:  # Define a volume to persist database data
